---
- hosts: 192.168.20.132
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios  # Specify the appropriate network operating system

  tasks:
    - name: Set IP address
      ios_config:
        lines:
          - ip address 192.168.100.200 255.255.255.0
          - no shutdown
        parents: interface FastEthernet2/0
      register: output

    - debug:
        msg: "{{ output }}"
