---
- hosts: 192.168.10.150
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: iosxr  # Specify the appropriate network operating system
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: set ip add
       iosxr_config:
        lines:
          - ip add 192.168.100.200 255.255.255.0
          - no shutdown
          - commit
        parents: interface gigabitEthernet0/0/0/2

    - name: set ip add2
       cisco.iosxr.iosxr_config:
        lines:
          - ip add 192.168.100.300 255.255.255.0
          - no shutdown
          - commit
        parents: interface gigabitEthernet0/0/0/3

    - name: set ip add
       cisco.iosxr.iosxr_config:
        lines:
          - ip add 192.168.100.200 255.255.255.0
          - no shutdown
          - commit
        parents: interface gigabitEthernet0/0/0/4


      register: output
    - debug:
        msg: "{{output}}"
