- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install bind-utils on Red Hat systems
      yum:
        name: bind-utils
      when: ansible_os_family == "RedHat"

    - name: Install dnsutils on Debian systems
      apt:
        name: dnsutils
      when: ansible_os_family == "Debian"
