---
- name: Configure VLANs on IOSXR
  hosts: 192.168.10.150
  tasks:
    - name: Configure VLANs
       cisco.ios.ios_vlans:
        vlans:
          - id: 10
            name: VLAN10
          - id: 20
            name: VLAN20
        state: present
  register: output
  -debug:
